### ISSUE TITLE
disqusShortname is not working

### ISSUE THREAD

**Issue by ghost** [hbpasti/heather-hugo#8]
Hi,

I am trying to enable disqus comments. But it is not working with this theme. Is there any work around ?

**Comment by hbpasti** [comment]
Hi, sorry for the long delay.

My intention with heather-hugo was only to adapt the jekyll theme to use it with hugo. I don't intend to (actually I can't) add any features to it, in order to keep with the "hyperminimal" design.

But have you tried the guidance in  ["comments in hugo"](https://gohugo.io/extras/comments/)? It worked fine for me. You would have to adapt `layouts/_default/single.html`, but only to add one line:

```
{{ template "_internal/disqus.html" . }}
```

Cheers,
